name: ExtDN M2 Coding Standard
on:
  push:
    branches:
      - 0.x
      - 1.x
      - 2.x
  pull_request:
    branches:
      - 0.x
      - 1.x
      - 2.x

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-coding-standard/8.4@master
