name: ExtDN M2 PHPStan
on: [ push, pull_request ]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: ethanyehuda/magento2-cronjobmanager
